spring.application.name=ecommerce-platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/ecommerce_platform_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.probes.enabled=true
management.endpoint.health.probes.enable=true

logging.level.com.namnguyen.ecommerce_platform=DEBUG

spring.config.import=optional:file:.env[.properties]
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [correlationId=%X{correlationId}] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [correlationId=%X{correlationId}] %logger{36} - %msg%n

# Active log file
logging.file.name=logs/ecommerce.log

# Archived log filename
logging.logback.rollingpolicy.file-name-pattern=logs/ecommerce.%d{yyyy-MM-dd}.%i.log.gz

# Rotate when current log reaches this size
logging.logback.rollingpolicy.max-file-size=10MB

# Retain approximately 14 daily history periods
logging.logback.rollingpolicy.max-history=14

# Do not allow archived logs to consume more than this
logging.logback.rollingpolicy.total-size-cap=500MB

# Apply retention cleanup when application starts
logging.logback.rollingpolicy.clean-history-on-start=true